import type { Role } from "@/lib/roles";

/** Menú lateral esperado por rol (SYSTRON). Alineado al Discovery funcional. */
export const SYSTRON_NAV: Partial<Record<Role, readonly string[]>> = {
  VENTAS: [
    "/panel",
    "/cotizaciones",
    "/ventas",
    "/clientes",
    "/prospectos",
    "/equipos",
    "/servicios/diagnostico",
    "/servicios/reparacion",
    "/servicios/garantia",
    "/cobranza",
    "/facturacion",
    "/pagos",
    "/personal/horas",
  ],
  TECNICO: ["/panel", "/operacion", "/personal/horas"],
  SUPERVISOR_TECNICO: [
    "/panel",
    "/personal/horas",
    "/servicios/diagnostico",
    "/servicios/reparacion",
    "/servicios/garantia",
    "/operacion",
    "/equipos",
    "/motores",
    "/reportes",
  ],
  GERENTE_OPERATIVO_SYSTRON: [
    "/panel",
    "/compras",
    "/personal/horas",
    "/reportes",
    "/servicios/diagnostico",
    "/servicios/reparacion",
    "/servicios/garantia",
    "/operacion",
    "/equipos",
    "/motores",
    "/proveedores",
    "/inventario",
    "/custodia",
  ],
  ALMACEN: ["/custodia", "/inventario", "/personal/horas", "/reportes"],
  COORDINACION_ADMINISTRACION: [
    "/panel",
    "/clientes",
    "/prospectos",
    "/cotizaciones",
    "/ventas",
    "/facturacion",
    "/cobranza",
    "/pagos",
    "/compras",
    "/finanzas",
    "/personal",
    "/personal/asistencia",
    "/nomina",
    "/comisiones",
    "/reportes",
    "/proveedores",
  ],
  AYUDANTE_GENERAL: [],
  KIOSCO_ASISTENCIA: ["/kiosco"],
};

export const SYSTRON_NAV_FORBIDDEN: Partial<Record<Role, readonly string[]>> = {
  VENTAS: ["/compras", "/finanzas", "/proveedores", "/usuarios", "/configuracion", "/inventario", "/custodia", "/nomina", "/produccion", "/agenda", "/operacion", "/motores"],
  TECNICO: [
    "/inicio",
    "/clientes",
    "/prospectos",
    "/cotizaciones",
    "/ventas",
    "/agenda",
    "/facturacion",
    "/cobranza",
    "/pagos",
    "/compras",
    "/finanzas",
    "/servicios/diagnostico",
    "/servicios/reparacion",
    "/servicios/garantia",
    "/equipos",
    "/motores",
    "/custodia",
    "/proveedores",
  ],
  COORDINACION_ADMINISTRACION: [
    "/servicios/diagnostico",
    "/servicios/reparacion",
    "/servicios/garantia",
    "/operacion",
    "/equipos",
    "/motores",
    "/custodia",
    "/inventario",
  ],
  ALMACEN: [
    "/inicio",
    "/panel",
    "/clientes",
    "/prospectos",
    "/cotizaciones",
    "/operacion",
    "/servicios/diagnostico",
    "/servicios/reparacion",
    "/servicios/garantia",
    "/equipos",
    "/motores",
  ],
  GERENTE_OPERATIVO_SYSTRON: [
    "/clientes",
    "/prospectos",
    "/cotizaciones",
    "/ventas",
    "/agenda",
    "/facturacion",
    "/cobranza",
    "/pagos",
    "/finanzas",
    "/nomina",
    "/produccion",
  ],
};

/** Menú lateral esperado por rol en empresa Servomotores. */
export const SERVOMOTORES_NAV: Partial<Record<Role, readonly string[]>> = {
  GERENTE_OPERATIVO_SERVOMOTORES: [
    "/panel",
    "/cotizaciones",
    "/clientes",
    "/prospectos",
    "/ventas",
    "/agenda",
    "/facturacion",
    "/cobranza",
    "/pagos",
    "/compras",
    "/servicios/diagnostico",
    "/servicios/reparacion",
    "/servicios/garantia",
    "/operacion",
    "/personal/horas",
    "/produccion",
    "/reportes",
    "/equipos",
    "/motores",
    "/custodia",
    "/inventario",
    "/proveedores",
  ],
};

export const SERVOMOTORES_NAV_FORBIDDEN: Partial<Record<Role, readonly string[]>> = {
  GERENTE_OPERATIVO_SERVOMOTORES: [
    "/inicio",
    "/finanzas",
    "/nomina",
    "/comisiones",
    "/personal",
    "/personal/asistencia",
    "/usuarios",
    "/configuracion",
    "/pruebas",
    "/kiosco",
  ],
};
