import type { Role } from "@/lib/roles";

/** Menú lateral esperado por rol (SYSTRON). Alineado al Discovery funcional. */
export const SYSTRON_NAV: Partial<Record<Role, readonly string[]>> = {
  VENTAS: [
    "/panel",
    "/cotizaciones",
    "/ventas",
    "/clientes",
    "/prospectos",
    "/equipos",
    "/servicios/activos",
    "/servicios/historial",
    "/cobranza",
    "/facturacion",
    "/pagos",
    "/personal/horas",
  ],
  TECNICO: [
    "/panel",
    "/servicios/activos",
    "/servicios/historial",
    "/personal/horas",
  ],
  SUPERVISOR_TECNICO: [
    "/panel",
    "/servicios/activos",
    "/servicios/historial",
    "/personal/horas",
    "/reportes",
  ],
  GERENTE_OPERATIVO_SYSTRON: [
    "/panel",
    "/compras",
    "/personal/horas",
    "/reportes",
    "/servicios/activos",
    "/servicios/historial",
    "/operacion",
    "/equipos",
    "/motores",
    "/proveedores",
    "/inventario",
    "/custodia",
  ],
  ALMACEN: ["/custodia", "/inventario", "/personal/horas", "/reportes"],
  CEO: [
    "/panel?vista=autorizacion",
    "/panel?vista=comercial",
    "/panel?vista=tecnico",
    "/panel?vista=admin",
    "/panel?vista=finanzas",
    "/clientes",
    "/prospectos",
    "/cotizaciones",
    "/cotizaciones?vista=pendientes",
    "/ventas",
    "/agenda",
    "/agenda#metas",
    "/produccion",
    "/reportes/conversion",
    "/equipos",
    "/motores",
    "/operacion?vista=validacion",
    "/operacion?vista=activas",
    "/servicios/garantia",
    "/custodia",
    "/inventario",
    "/operacion",
    "/compras?vista=directas",
    "/compras?vista=oc",
    "/compras?vista=autorizar",
    "/compras?vista=procesar",
    "/proveedores",
    "/facturacion?vista=solicitudes",
    "/facturacion?vista=facturas",
    "/facturacion?vista=remisiones",
    "/facturacion?vista=canceladas",
    "/pagos?vista=pendientes",
    "/pagos?vista=validados",
    "/cobranza?vista=cxc",
    "/cobranza?vista=vencidas",
    "/cobranza",
    "/finanzas",
    "/finanzas?vista=movimientos",
    "/finanzas?vista=ingresos",
    "/finanzas?vista=egresos",
    "/finanzas?vista=cuentas",
    "/finanzas?vista=transferencias",
    "/finanzas?vista=cxp",
    "/personal",
    "/personal/asistencia",
    "/personal/asistencia?vista=vacaciones",
    "/personal/horas",
    "/personal?vista=documentos",
    "/nomina",
    "/nomina?vista=actual",
    "/nomina?vista=extraordinarios",
    "/nomina?vista=aguinaldo",
    "/comisiones",
    "/nomina?vista=documentos",
    "/reportes/cotizaciones",
    "/reportes/diagnosticos",
    "/reportes/reparaciones",
    "/reportes/inventario",
    "/reportes/movimientos",
    "/reportes/cxp",
    "/reportes/cxc",
    "/reportes/nomina",
    "/configuracion#identidad",
    "/configuracion#prioridades",
    "/usuarios",
  ],
  COORDINACION_ADMINISTRACION: [
    "/panel?vista=pendientes",
    "/cobranza?vista=vencidas",
    "/clientes",
    "/cotizaciones",
    "/ventas",
    "/prospectos",
    "/facturacion?vista=solicitudes",
    "/facturacion?vista=facturas",
    "/facturacion/nuevo",
    "/facturacion?vista=canceladas",
    "/facturacion?vista=remisiones",
    "/pagos?vista=pendientes",
    "/pagos?vista=validados",
    "/cobranza?vista=cxc",
    "/cobranza",
    "/compras?vista=directas",
    "/compras?vista=oc",
    "/compras?vista=procesar",
    "/proveedores",
    "/finanzas",
    "/finanzas?vista=movimientos",
    "/finanzas?vista=ingresos",
    "/finanzas?vista=egresos",
    "/finanzas?vista=transferencias",
    "/finanzas?vista=cuentas",
    "/finanzas?vista=cxp",
    "/personal",
    "/personal/asistencia",
    "/personal/asistencia?vista=vacaciones",
    "/personal?vista=documentos",
    "/comisiones",
    "/nomina",
    "/nomina?vista=actual",
    "/nomina?vista=incidencias",
    "/nomina?vista=documentos",
    "/nomina?vista=extraordinarios",
    "/nomina?vista=aguinaldo",
    "/reportes/movimientos",
    "/reportes/cxp",
    "/reportes/cxc",
    "/reportes/nomina",
  ],
  AYUDANTE_GENERAL: [],
  KIOSCO_ASISTENCIA: ["/kiosco"],
};

export const SYSTRON_NAV_FORBIDDEN: Partial<Record<Role, readonly string[]>> = {
  VENTAS: ["/compras", "/finanzas", "/proveedores", "/usuarios", "/configuracion", "/inventario", "/custodia", "/nomina", "/produccion", "/agenda", "/operacion", "/motores", "/servicios/diagnostico", "/servicios/reparacion", "/servicios/garantia"],
  TECNICO: [
    "/inicio",
    "/clientes",
    "/prospectos",
    "/cotizaciones",
    "/ventas",
    "/agenda",
    "/facturacion",
    "/cobranza",
    "/pagos",
    "/compras",
    "/finanzas",
    "/operacion",
    "/equipos",
    "/motores",
    "/custodia",
    "/proveedores",
    "/reportes",
  ],
  SUPERVISOR_TECNICO: [
    "/operacion",
    "/equipos",
    "/motores",
    "/custodia",
    "/inventario",
    "/compras",
    "/finanzas",
    "/servicios/diagnostico",
    "/servicios/reparacion",
    "/servicios/garantia",
  ],
  COORDINACION_ADMINISTRACION: [
    "/servicios/diagnostico",
    "/servicios/reparacion",
    "/servicios/garantia",
    "/operacion",
    "/equipos",
    "/motores",
    "/custodia",
    "/inventario",
  ],
  ALMACEN: [
    "/inicio",
    "/panel",
    "/clientes",
    "/prospectos",
    "/cotizaciones",
    "/operacion",
    "/servicios",
    "/servicios/diagnostico",
    "/servicios/reparacion",
    "/servicios/garantia",
    "/equipos",
    "/motores",
  ],
  GERENTE_OPERATIVO_SYSTRON: [
    "/clientes",
    "/prospectos",
    "/cotizaciones",
    "/ventas",
    "/agenda",
    "/facturacion",
    "/cobranza",
    "/pagos",
    "/finanzas",
    "/nomina",
    "/produccion",
  ],
};

/** Menú lateral esperado por rol en empresa Servomotores. */
export const SERVOMOTORES_NAV: Partial<Record<Role, readonly string[]>> = {
  GERENTE_OPERATIVO_SERVOMOTORES: [
    "/panel",
    "/cotizaciones",
    "/clientes",
    "/prospectos",
    "/ventas",
    "/agenda",
    "/facturacion",
    "/cobranza",
    "/pagos",
    "/compras",
    "/servicios/activos",
    "/servicios/historial",
    "/operacion",
    "/personal/horas",
    "/produccion",
    "/reportes",
    "/motores",
    "/custodia",
    "/inventario",
    "/proveedores",
  ],
};

export const SERVOMOTORES_NAV_FORBIDDEN: Partial<Record<Role, readonly string[]>> = {
  GERENTE_OPERATIVO_SERVOMOTORES: [
    "/inicio",
    "/equipos",
    "/finanzas",
    "/nomina",
    "/comisiones",
    "/personal",
    "/personal/asistencia",
    "/usuarios",
    "/configuracion",
    "/pruebas",
    "/kiosco",
  ],
};
